<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Whizdom-Trainings" ignored="0" name="LoginTest" tests="2" failures="1" timestamp="2021-01-15T21:27:48 IST" time="29.772" errors="0">
  <testcase name="loginTest" time="13.102" classname="com.qtpselenium.hybrid.SuiteA.LoginTest">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
at com.qtpselenium.hybrid.driver.DriverScript.executeTest(DriverScript.java:33)
at com.qtpselenium.hybrid.SuiteA.LoginTest.loginTest(LoginTest.java:23)
at java.util.ArrayList.forEach(ArrayList.java:1259)
Caused by: java.lang.AssertionError: Expected Success but encountered Failure
at org.junit.Assert.fail(Assert.java:88)
at com.qtpselenium.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:137)
at com.qtpselenium.hybrid.keywords.AppKeywords.validateLogin(AppKeywords.java:11)
... 39 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="13.97" classname="com.qtpselenium.hybrid.SuiteA.LoginTest"/>
</testsuite> <!-- LoginTest -->
